[meta]
authors=["singlestore"]
title="Getting Started With CDC Replication from MongoDB"
description="""\
    Setup Zero ETL data replication from MongoDB to SingleStore \
    """
icon="pipeline"
difficulty="beginner"
tags=["cdc", "mongo", "kai"]
lesson_areas=["Data Management"]
destinations=["spaces"]
minimum_tier="standard"
