[meta]
author="singlestore"
title="Semantic Search with OpenAI QA"
description="""\
    Provide context to chatGPT using data stored in SingleStoreDB. \
    """
icon="crystal-ball"
difficulty="beginner"
tags=["starter", "openai", "vectordb", "genai"]
lesson_areas=["AI"]
destinations=["spaces"]
minimum_tier="free-shared"
