[meta]
title="Semantic Search with OpenAI Embedding Creation"
description="""\
    Generate embeddings and run semantic search in your database in SQL. \
    """
icon="chart-network"
difficulty="Beginner"
tags=["starter", "openai", "vectordb", "genai"]
lesson_areas=["AI"]
destinations=["spaces"]
minimum_tier="free-shared"
