[meta]
title="Real-Time Anomaly Detection"
description="""\
    Real-time anomaly detection in IoT sensor data, harnessing the robust capabilities of SingleStoreDB and advanced analytical techniques. \
    """
icon="chart-scatter"
difficulty="Intermediate"
tags=["vectordb", "realtime"]
lesson_areas=["AI", "Real-time"]
destinations=["spaces"]
minimum_tier="standard"
