[meta]
title="Load JSON files with Pipeline from S3"
description="""\
    This notebook will help you load JSON files from a public open AWS S3 bucket.
    """
icon="chart-network"
difficulty="Beginner"
tags=["advanced", "pipeline", "json", "s3"]
lesson_areas=["Ingest"]
destinations=["spaces"]
minimum_tier="standard"
