[meta]
title="Getting Started with Notebooks"
description="""\
    SingleStore Notebooks with an AI Copilot (SQrL) for data prototyping, \
    visualization and analysis. \
    """
icon="notes"
difficulty="Beginner"
tags=["starter", "python", "sqrl"]
lesson_areas=["Python SDK"]
destinations=["spaces"]
minimum_tier="free-shared"
