[meta]
title="Unified Data Analysis: SQL & NoSQL on a Single Database with Kai"
description="""\
    Perform both SQL and NoSQL queries on multi-modal relational and JSON data \
    """
icon="database"
tags=["CDC", "mongo", "SQL", "NoSQL", "kai"]
destinations=["spaces"]
