[meta]
authors=["singlestore"]
title="Unified Data Analysis: SQL & NoSQL on a Single Database with Kai"
description="""\
    Perform both SQL and NoSQL queries on multi-modal relational and JSON data \
    """
icon="database"
difficulty="intermediate"
tags=["cdc", "mongo", "sql", "nosql", "kai"]
lesson_areas=["Kai"]
destinations=["spaces"]
minimum_tier="standard"
