[meta]
author="singlestore"
title="Integrating pandas with SingleStoreDB"
description="""\
    Moving data to and from pandas DataFrames is demonstrated using
    the SingleStoreDB Python library, SQLAlchemy, and Ibis.
    """
icon="database"
difficulty="beginner"
tags=["starter", "dataframe", "python"]
lesson_areas=["Python SDK"]
destinations=["spaces"]
minimum_tier="free-shared"
