[meta]
author="singlestore"
title="Database Performance Troubleshoot Notebook"
description="""\
    This notebook will help you perform database performance troubleshoot
"""
icon="database"
difficulty="advanced"
tags=["troubleshoot", "performance", "tuning", "starter"]
lesson_areas=["Query Performance"]
destinations=["spaces"]
minimum_tier="standard"
