[meta]
title="Kafka Pipelines and Query Tuning"
description="""\
    Create a SingleStore pipeline to track the International Space Station and adjust queries & schema to optimize performance.
    """
difficulty="advanced"
tags=["beginner", "kafka", "pipeline", "querytuning"]
lesson_areas=["Query Performance", "Ingest"]
icon="database"
destinations=["spaces"]
minimum_tier="standard"
