[meta]
title="How to Build LLM Apps that can See Hear Speak"
description="""\
    Using OpenAI to build an app that can take images, audio, and text data to generate output
    """
icon="chart-network"
difficulty="Intermediate"
tags=["advanced", "openai", "genai", "vectordb"]
lesson_areas=["AI"]
destinations=["spaces"]
minimum_tier="standard"
