[meta]
authors=["singlestore"]
title="Mongo Atlas & SingleStore Kai"
description="""\
    Run your MongoDB queries on SingleStore Kai with no code change. \
    """
icon="database"
difficulty="beginner"
tags=["starter", "mongo", "kai"]
lesson_areas=["Kai"]
destinations=["spaces"]
minimum_tier="free-shared"
