[meta]
title="Movie Recommendation"
description="""\
    Movie recommendation engine using vectors stored in SingleStore to find your next watch. \
    """
icon="camera-movie"
difficulty="Intermediate"
tags=["advanced", "vectordb", "genai", "openai"]
lesson_areas=["AI"]
destinations=["spaces"]
minimum_tier="standard"
