[meta]
author="singlestore"
title = "Backup Database to AWS S3"
description = """\
    Performs backup either single or multiple databases to AWS S3. \
    """
icon = "database"
difficulty="beginner"
tags = ["starter", "backup"]
lesson_areas=["Data Management"]
destinations = ["spaces"]
minimum_tier="standard"
