[meta]
authors=["singlestore"]
title="Resume Evaluator with Vector Index"
description="""\
    Resume Evaluator using vectors stored in SingleStore to find sutiable resume for your job description, with Indexed ANN search.\
    """
icon="arrows-spin"
difficulty="intermediate"
tags=["vectordb", "genai", "openai", "rag"]
lesson_areas=["AI"]
destinations=["spaces"]
minimum_tier="free-shared"
