[meta]
title="Load files from S3 into Shared Tier"
description="""\
    This notebook guides you through data ingestion of CSV files from an AWS S3 location into your shared tier workspace. \
    """
icon="chart-network"
difficulty="beginner"
tags=["pipeline", "s3"]
lesson_areas=["Ingest"]
destinations=["spaces"]
minimum_tier="standard"
