[meta]
author="singlestore"
title = "Ingest data from Confluent Cloud (Kafka)"
description = """
    A step-by-step guide on seamlessly ingesting data from Confluent Cloud (Kafka) into your SingleStoreDB database using a robust pipeline. """
icon = "confluent-logo"
difficulty="intermediate"
tags = ["advanced", "confluent", "kafka", "pipeline", "realtime"]
lesson_areas=["Integrations"]
destinations = ["spaces"]
minimum_tier="standard"
